apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient
        image: hasinij4567/patient-service:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: patient-config
              key: PORT
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: patient-secret
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: patient-secret
              key: JWT_SECRET
