version: '3.9'

services:
  notification-db:
    image: mongo:7
    container_name: notification-db
    ports:
      - "27019:27017"
    volumes:
      - notification-db-data:/data/db

  notification-service:
    build: .
    container_name: notification-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://notification-db:27017/notificationdb
    depends_on:
      - notification-db

volumes:
  notification-db-data:
